### PR TITLE
add missing Paws::Credential::None->new default behavior

### PR DESCRIPTION
**Pull request by cakirkeMSTS**
resolve issue #2

### CODE REVIEW

**Review by daadiutori — COMMENTED** [review]
Changes make sense.

**Review by daadiutori — APPROVED** [review]

**Review by robmarlow — APPROVED** [review]
this fixed my issue

**Review by hank-paramount — APPROVED** [review]
I approve this...as long as it works.

**Comment by Prajithp** [comment]
will do the release sometime this week. Thanks guys :)

**Comment by daadiutori** [comment]
Thanks!

**Pull request merged**
